### ISSUE TITLE
Describe loci in a scheme

### ISSUE THREAD

**Issue by lskatz** [lskatz/mlst-hash-template#34]
Need file to describe all the loci in a scheme. Otherwise callers cannot output a proper profiles file and know all the loci it missed. I'm sure there are other reasons.

One way to do this would be to make it a yaml file and define the yaml file in the spec.

Here is a first shot at it.

```yml
scheme: senterica
  - loci:
    - aroC
    - dnaN
    - hemD
    - hisD
    - purE
    - sucA
    - thrA
 ```

I could potentially add in locus properties too, following what BigsDB does as shown here: 
![image](https://user-images.githubusercontent.com/14798/235248964-262b83a9-adaf-408d-bb7c-3506a557c580.png)

And [more context here](https://bigsdb.readthedocs.io/en/latest/database_schema.html).
